#!/bin/bash
unset OS_USERNAME OS_PASSWORD OS_PROJECT_NAME OS_AUTH_URL OS_IDENTITY_API_VERSION OS_SYSTEM_SCOPE OS_PROJECT_ID

export OS_USERNAME=$1
export OS_PASSWORD=$2
export OS_PROJECT_NAME=$3
export OS_USER_DOMAIN_ID=default
export OS_PROJECT_DOMAIN_ID=default
export OS_AUTH_URL=http://127.0.0.1/identity
export OS_IDENTITY_API_VERSION=3
